[build]
builder = "nixpacks"
buildCommand = "npm run clean && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
